import dotenv from 'dotenv';
dotenv.config();

export const env = {
  nodeEnv: process.env.NODE_ENV || 'development',
  port: parseInt(process.env.PORT || '3000', 10),
  mongodbUri: process.env.MONGODB_URI || 'mongodb://localhost:27017/erpFactory',
  redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
  jwtSecret: process.env.JWT_SECRET || 'dev-jwt-secret',
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || 'dev-refresh-secret',
  jwtAccessExpiry: process.env.JWT_ACCESS_EXPIRY || '15m',
  jwtRefreshExpiry: process.env.JWT_REFRESH_EXPIRY || '7d',
  corsOrigin: process.env.CORS_ORIGIN || 'http://localhost:5173',
  emailNotifications: process.env.EMAIL_NOTIFICATIONS === 'true',
  smtpHost: process.env.SMTP_HOST || '',
  smtpPort: parseInt(process.env.SMTP_PORT || '587', 10),
  smtpSecure: process.env.SMTP_SECURE === 'true',
  smtpUser: process.env.SMTP_USER || '',
  smtpPass: process.env.SMTP_PASS || '',
  smtpFrom: process.env.SMTP_FROM || '',
  s3Bucket: process.env.S3_BUCKET || '',
  s3Region: process.env.S3_REGION || 'ap-south-1',
  redisKeyPrefix: process.env.REDIS_KEY_PREFIX || 'erp:',
  twofactorApiKey: String(process.env.TWOFACTOR_API_KEY || '').trim(),
  twofactorOtpTemplateName: String(process.env.TWOFACTOR_OTP_TEMPLATE_NAME || 'OTPtemplate').trim(),
  twofactorBaseUrl: String(process.env.TWOFACTOR_BASE_URL || 'https://2factor.in').trim().replace(/\/$/, ''),
  appleReviewOtpEnabled: !['false', '0', 'no', 'off'].includes(
    String(process.env.APPLE_REVIEW_OTP_ENABLED ?? 'false').toLowerCase(),
  ),
  appleReviewPhone: String(process.env.APPLE_REVIEW_PHONE || '').trim(),
  appleReviewOtp: String(process.env.APPLE_REVIEW_OTP || '').trim(),
  otpRegisterEnabled: !['false', '0', 'no', 'off'].includes(
    String(process.env.AUTH_OTP_REGISTER_ENABLED ?? 'false').toLowerCase(),
  ),
  authPhoneOtpOnly: ['true', '1', 'yes', 'on'].includes(
    String(process.env.AUTH_PHONE_OTP_ONLY ?? 'false').toLowerCase(),
  ),
  cookieDomain: String(process.env.COOKIE_DOMAIN || '').trim(),
  cookieSameSite: String(process.env.COOKIE_SAMESITE || 'lax').toLowerCase(),
  otpIpSoftLimit: parseInt(process.env.OTP_IP_SOFT_LIMIT || '', 10) || 0,
  otpIpSoftWindowSec: parseInt(process.env.OTP_IP_SOFT_WINDOW_SEC || '', 10) || 3600,
  otpRateLimit: parseInt(process.env.OTP_RATE_LIMIT || '', 10) || 0,
  otpRateWindowSec: parseInt(process.env.OTP_RATE_WINDOW_SEC || '', 10) || 3600,
  loginRateLimit: parseInt(process.env.LOGIN_RATE_LIMIT || '', 10) || 0,
  loginRateWindowSec: parseInt(process.env.LOGIN_RATE_WINDOW_SEC || '', 10) || 3600,
  verifyOtpRateLimit: parseInt(process.env.VERIFY_OTP_RATE_LIMIT || '', 10) || 0,
  verifyOtpRateWindowSec: parseInt(process.env.VERIFY_OTP_RATE_WINDOW_SEC || '', 10) || 3600,
  rateLimitRedisTimeoutMs: parseInt(process.env.RATE_LIMIT_REDIS_TIMEOUT_MS || '2000', 10),
};
